name: checkcheckcheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.3.0
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  english_words: ^4.0.0
  intl: ^0.17.0
  cupertino_icons : ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
