// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqfKuRIBmbrUD3Xy8MFkNuhEwNCOsn1k',
    appId: '1:627662526322:web:0a7d06a1a0c25e73a72feb',
    messagingSenderId: '627662526322',
    projectId: 'buccheck',
    authDomain: 'buccheck.firebaseapp.com',
    storageBucket: 'buccheck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaJRmUFRSVBa6yT1YnkxegIrAfzBXemow',
    appId: '1:627662526322:android:6e50543aab03e202a72feb',
    messagingSenderId: '627662526322',
    projectId: 'buccheck',
    storageBucket: 'buccheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4OC6mrtxzKarH8F66RFzYUppa0eJgYA',
    appId: '1:627662526322:ios:be6c71d1c3ad91baa72feb',
    messagingSenderId: '627662526322',
    projectId: 'buccheck',
    storageBucket: 'buccheck.appspot.com',
    iosBundleId: 'com.example.checkcheckcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4OC6mrtxzKarH8F66RFzYUppa0eJgYA',
    appId: '1:627662526322:ios:be6c71d1c3ad91baa72feb',
    messagingSenderId: '627662526322',
    projectId: 'buccheck',
    storageBucket: 'buccheck.appspot.com',
    iosBundleId: 'com.example.checkcheckcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqfKuRIBmbrUD3Xy8MFkNuhEwNCOsn1k',
    appId: '1:627662526322:web:d1884ebda47f08f8a72feb',
    messagingSenderId: '627662526322',
    projectId: 'buccheck',
    authDomain: 'buccheck.firebaseapp.com',
    storageBucket: 'buccheck.appspot.com',
  );
}
